name: slack-tag-events

on:
  create:
    tags:
      - "*"
  delete:
    tags:
      - "*"

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
        run: |
          # Extract event data
          EVENT_TYPE="${{ github.event_name }}"
          REF="${{ github.event.ref }}"
          ACTOR="${{ github.actor }}"
          REPO_NAME="${{ github.repository }}"
          REPO_URL="https://github.com/${{ github.repository }}"
          TAG_URL="https://github.com/${{ github.repository }}/releases/tag/${REF#refs/tags/}"
          TIMESTAMP=$(date -u)

          # Determine action type
          if [[ "$EVENT_TYPE" == "create" ]]; then
            ACTION="Created"
          elif [[ "$EVENT_TYPE" == "delete" ]]; then
            ACTION="Deleted"
          fi

          # Initialize release name
          RELEASE_NAME="None"

          # Fetch release info only when tag is created
          if [[ "$ACTION" == "Created" ]]; then
            # Get release information using the GitHub API
            # Check if a release exists for the tag
            RELEASE_NAME=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/tags/${REF#refs/tags/}" | \
              jq -r '.name // "None"')
          fi

          # Start building the Slack message
          MESSAGE="{
            \"blocks\": [
              {
                \"type\": \"header\",
                \"text\": {
                  \"type\": \"plain_text\",
                  \"text\": \"Tag Event: $ACTION\",
                  \"emoji\": true
                }
              },
              {
                \"type\": \"section\",
                \"fields\": [
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Tag Name:* <${TAG_URL}|$REF>\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Action:* $ACTION\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*User:* $ACTOR\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Repository:* <$REPO_URL|$REPO_NAME>\"
                  },
                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Timestamp:* $TIMESTAMP\"
                  }
                ]
              }"

          # Add release information if tag was created and associated with a release
          if [[ "$ACTION" == "Created" && "$RELEASE_NAME" != "None" ]]; then
            MESSAGE+=", {
              \"type\": \"section\",
              \"fields\": [
                {
                  \"type\": \"mrkdwn\",
                  \"text\": \"*Release:* $RELEASE_NAME\"
                }
              ]
            }"
          fi

          MESSAGE+="]
        }"

          # Send message to Slack
          curl -X POST \
            -H 'Content-type: application/json; charset=utf-8' \
            --data "$MESSAGE" \
          $SLACK_WEBHOOK_URL
