name: Release Tag Notification

on:
  release:
    types: [created, deleted]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    
    # Skip if the event is related to pull requests
    if: >
      github.event.pull_request == null &&
      !contains(github.event.action, 'pull_request')
    
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Release Tag ${{ github.event.action }}*\n\n• Repository: ${{ github.repository }}\n• Ref: ${{ github.ref_name }}\n• Action: ${{ github.event.action }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Triggered by: ${{ github.actor }}"
                    }
                  ]
                }
              ]
            }
